### PR TITLE
Remove strict versioning on clap dependency

### PR DESCRIPTION
**Pull request by CookieComputing**
Addresses https://github.com/virtee/snpguest/issues/68. I think it should be fine to remove this strict semvar, but happy to make any changes you folks see fit!

### CODE REVIEW

**Review by tylerfanelli — APPROVED** [review]
LGTM, please add a `Signed-off-by` line to the commit.

**Comment by CookieComputing** [comment]
I'll also update the MSRV in this repo as well so we can keep it consistent on `snphost` (see my PR in https://github.com/virtee/snphost/pull/74)

**Comment by tylerfanelli** [comment]
Can you update to 1.79 instead?

**Comment by larrydewey** [comment]
Looks like we can go up to 1.80, even:
image

**Comment by tylerfanelli** [comment]
Sure, 1.80 works. @CookieComputing do you mind updating this and snphost's PR to 1.80?

**Review by tylerfanelli — APPROVED** [review]

**Comment by tylerfanelli** [comment]
I'll update the toolchain. Thanks @CookieComputing

**Comment by CookieComputing** [comment]
Thanks! I'll submit another PR for just updating the toolchain to 1.80 and check to see that it builds against `cargo build` for both repos

**Pull request merged**
